on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install
      - run: npm run lint

  test-integration-with-adb-serial-port:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        recipe_uuid:
          - ea5fda48-fa8b-48c1-8acc-07d910856141 # android 8.1

    name: With Adb Serial Port
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12.0"

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Start Genymotion Cloud SaaS instance
        uses: ./
        with:
          api_token: ${{ secrets.GMSAAS_APITOKEN }}
          recipe_uuid: ${{ matrix.recipe_uuid }}
          adb_serial_port: "47021"
  
  test-integration-several_devices:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        recipe_uuid:
          - ea5fda48-fa8b-48c1-8acc-07d910856141 # android 8.1
          - 4c015ada-e64e-4f5d-a320-06cbf6e95648 # android 10

    name: Start Several devices
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12.0"

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Genymotion
        uses: ./
        with:
          recipe_uuid: ${{ matrix.recipe_uuid }}
          api_token: ${{ secrets.GMSAAS_APITOKEN }}

  test-integration-specific_gmsaas_version:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        recipe_uuid:
          - 4c015ada-e64e-4f5d-a320-06cbf6e95648 # android 10

    name: Use a specific gmsaas version
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12.0"

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Genymotion
        uses: ./
        with:
          gmsaas_version: "1.12.0"
          api_token: ${{ secrets.GMSAAS_APITOKEN }}


  test-integration-install_configure_gmsaas:
    runs-on: ubuntu-latest

    name: Only install and configure gmsaas
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12.0"

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Genymotion
        uses: ./
        with:
          api_token: ${{ secrets.GMSAAS_APITOKEN }}
